DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS url_checks;

CREATE TABLE urls (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) UNIQUE NOT NULL,
    created_at timestamp NOT NULL
    );

CREATE TABLE url_checks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id bigint REFERENCES urls (id) ON DELETE CASCADE NOT NULL,
    status_code integer NOT NULL,
    h1 varchar(255),
    title varchar(255),
    description text,
    created_at date NOT NULL
    );